import * as fs from "fs/promises";
import * as path from "path";
import type { GraphState } from "../domain/types.js";

/**
 * Write all analysis reports to the output directory.
 * Mirrors the input directory structure in output/.
 * Returns the list of file paths written.
 */
export async function writeReports(state: GraphState): Promise<string[]> {
  const { outputDir, imageResults, seriesResults, evolutionResult } = state;
  const written: string[] = [];

  // Ensure output root exists
  await fs.mkdir(outputDir, { recursive: true });

  // Write per-image JSON files
  for (const analysis of imageResults) {
    const seriesDir = path.join(outputDir, analysis.seriesId);
    await fs.mkdir(seriesDir, { recursive: true });

    const imageName = path.basename(analysis.imagePath, path.extname(analysis.imagePath));
    const jsonPath = path.join(seriesDir, `${imageName}_analysis.json`);
    await fs.writeFile(jsonPath, JSON.stringify(analysis, null, 2), "utf-8");
    written.push(jsonPath);
  }

  // Write per-series Markdown summaries
  for (const summary of seriesResults) {
    const seriesDir = path.join(outputDir, summary.seriesId);
    await fs.mkdir(seriesDir, { recursive: true });

    const mdPath = path.join(seriesDir, "series_summary.md");
    const content = buildSeriesMarkdown(summary);
    await fs.writeFile(mdPath, content, "utf-8");
    written.push(mdPath);
  }

  // Write evolution analysis files
  if (evolutionResult) {
    const evolutionJsonPath = path.join(outputDir, "evolution_analysis.json");
    await fs.writeFile(evolutionJsonPath, JSON.stringify(evolutionResult, null, 2), "utf-8");
    written.push(evolutionJsonPath);

    const combinedMdPath = path.join(outputDir, "combined_diagnostic_report.md");
    const combinedContent = buildCombinedMarkdown(evolutionResult);
    await fs.writeFile(combinedMdPath, combinedContent, "utf-8");
    written.push(combinedMdPath);
  }

  return written;
}

function buildSeriesMarkdown(summary: import("../domain/types.js").SeriesSummary): string {
  return `# Series Analysis: ${summary.seriesId}

> ${summary.disclaimer}

**Analyzed**: ${summary.processedAt}
**Images**: ${summary.imageCount} submitted, ${summary.successCount} successfully analyzed, ${summary.failureCount} failed
**Context file used**: ${summary.textContextUsed ? "Yes" : "No"}

## Primary Diagnosis
${summary.primaryDiagnosis} — Confidence: ${summary.confidenceLevel}

## Differential Diagnoses
${summary.differentialDiagnoses.length > 0 ? summary.differentialDiagnoses.map((d, i) => `${i + 1}. ${d}`).join("\n") : "_None noted_"}

## Consistent Findings Across All Views
${summary.consistentFindings.length > 0 ? summary.consistentFindings.map((f) => `- ${f}`).join("\n") : "_No consistent findings extracted_"}

## Discrepancies Between Views
${summary.discrepancies.length > 0 ? summary.discrepancies.map((d) => `- ${d}`).join("\n") : "_None noted_"}

## Full Series Report

${summary.report}

---
*Generated by AgenticMedicalImagingHelper v1.0.0 | Educational use only*
`;
}

function buildCombinedMarkdown(evolution: import("../domain/types.js").TemporalAnalysis): string {
  return `# Combined Diagnostic Report

> ${evolution.disclaimer}

**Generated**: ${evolution.processedAt}
**Series analyzed**: ${evolution.seriesCount} (${evolution.seriesIds.join(", ")})
**Overall progression**: ${evolution.progression}

## Temporal Evolution Analysis

${evolution.combinedReport}

## Treatment Recommendations
${evolution.treatmentRecommendations.length > 0 ? evolution.treatmentRecommendations.map((r) => `- ${r}`).join("\n") : "_See full report above_"}

---
*Generated by AgenticMedicalImagingHelper v1.0.0 | Educational use only*
*This report is AI-generated for educational purposes only. Professional clinical review required.*
`;
}
